navigation_map = {
  lateLogin: {
    lateLogin: "lateLogin",
    vectors: [
      "You are late for your shift!",
      "Unblock your meter device",
      "Request late login",
      "late",
      "late",
      "late",
      "Do you have a reason for a late login?",
      "Requesting a late login without justification will result in an internal fine, impacting your income.",
      "Please select a reason",
      "Report late login",
      "Your Late login request has been sent!",
      "It will take 10 to 15 minutes to unlock your meter.",
      "Your Late login has been accepted!",
      "Your Late login has been rejected!",
      "Your late login request is rejected, you will be charged with an internal fine.",
    ],
    id: 100,
    navigation: "lateLogin",
    navigationText: "Late Login.",
  },
  Notifications: {
    Notifications: "Notifications",
    vectors: [
      "Notifications",
      "All the latest news in a single page",
      "Sorting",
      "Newest first",
      "Reply to P&C",
      "Newest first",
      "Priority",
      "Unread first",
      "messages",
      "message",
      "read",
      "unread",
      "message",
      "news",
      "new message",
      "new messages",
      "massage",
      "priority",
      "newest first",
      "unread first",
      "new",
      "anything new",
    ],
    id: 200,
    navigation: "Notifications",
    navigationText: "Notifications.",
  },
  myCalendar: {
    myCalendar: "myCalendar",
    vectors: [
      "Calendar",
      "Your calendar",
      "my calendar",
      "November",
      "2024",
      "2025",
      "2026",
      "2027",
      "2028",
      "2029",
      "2030",
      "2031",
      "2032",
      "2033",
      "2034",
      "2035",
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "event",
      "November",
      "December",
      "Local leave",
      "Annual vehicle review",
      "Request a modification",
      "change date",
      "You dont have any appointment this month.",
      "appointment",
    ],
    id: 300,
    navigation: "myCalendar",
    navigationText: "My calendar.",
  },
  myFinances: {
    myFinances: "myFinances",
    vectors: [
      "collections",
      "Collections",
      "graph",
      "Finances",
      "Daily avg",
      "Commission",
      "Outstanding",
      "Account Statement",
      "Fine enquiry",
      "My Collections",
      "Total collections",
      "Daily avg",
      "Days collections",
      "Daily collections",
      "Commission",
      "Days worked",
      "Surcharges",
      "Shift collections details",
      "Day shift",
      "Night shift",
      "Day shift collections",
      "Night shift collections",
      "Commission",
      "Days worked",
      "forecast",
      "forcast",
      "Collections forecast",
      "Based on you current collections and your commission percentage, your collection forecast is:",
      "To achieve it, in the next days you will have to collect at least 500 AED per day.",
      "Outstanding details",
      "Account Statement",
      "Please choose Start and End date to create your report.",
      "Account Statement",
      "Fine enquiry",
      "Fine",
      "enquiry",
      "Your fines",
      "Internal Fine",
      "RTA fine",
      "Internal Fine",
      "Dispute fine",
      "Dispute",
      "fine",
      "RTA fine",
      "Open a new ticket",
      "want",
      "As a driver (User), I want to have access to a dashboard that provides me an overview of my earnings and expenses (Action) so that I can have a clear understanding of my financial perfomance (Outcome)",
      "User should be able to access My Finance via widget in the dashboard or the burger menu in the app’s main Dashboard",
      "He should be able to access My Collections, Outstanding, Fine enquiry and Account statements from here",
      "A widget should provide immediate insights to his monthly collection (2nd until the current date)",
    ],
    id: 400,
    navigationText: "Your Finance",
    navigation: "myFinances",
  },
  hr: {
    hr: "hr",
    vectors: [
      "HR",
      "Everything you need related to your leaves, documents and payslips",
      "Leaves",
      "Local leave, annual leave",
      "Documents",
      "Passport, insurance, VISA",
      "Passport collection",
      "Payslips",
      "talk to hr",
    ],
    id: 500,
    navigationText: "HR",
    navigation: "hr",
  },
  MyScore: {
    MyScore: "myScore",
    vectors: [
      "My Score",
      "Learn how to be a better driver",
      "overall score",
      "performance",
      "behaviour",
      "do you want to win AED",
      "reach in your behavioour score to get the bonus",
      "need to focus on",
      "fines",
      "complaints",
      "RTA quality",
      "your challenges",
      "challenges",
      "win rewards with zero traffic fines quality violations & customer complaints",
      "ct champions",
      "fly for free",
      "driver a taxi win a taxi",
      "driver comparison",
      "your score is not yet available. your have worked less than days. please check again",
      "overall score",
      "performance",
      "behaviour",
      "wahts new ",
      "customer satisfaction",
      "see what your customer think about you",
      "pts",
      "reviews",
      "behaviour bonus",
      "bonus",
      "want to win",
      "your challenges",
      "ct champions",
      "win a taxi",
      "go through months of your score",
      "score",
      "performance",
      "behavioud",
      "customer satisfaction",
      "see what your customer thinks about you",
      "reviews",
      "success trends",
      "trends",
      "points",
      "last month",
      "improvement trends",
      "pts",
      "As a driver (User), I want to access the Challenges (Action) so that I can see the requirements and my current status (Outcome)",
      "User should be able to access Challenges via a card in My Score page",
      "The page should provide the user all the information needed to get the bonus",
      "The user should understand if he’s eligible or not for it",
      "All challenges should be clickable for the user",
    ],
    id: 600,
    navigationText: "My Score",
    navigation: "myScore",
  },
  leaves: {
    leaves: "leaves",
    vectors: [
      "Leaves",
      "Your leaves in a single place.",
      "Your calendar",
      "Upcoming leaves",
      "You dont have any planned leaves.",
      "Previous leaves",
      "Request a new leave",
      "Previous leaves",
      "Approved",
      "Approve",
      "Local leave",
      "Cancelled",
      "Emergency leave",
      "Rejected",
      "cancel",
      "What kind of leave you need?",
      "A single day off you can take twice a month",
      "Authorized time off employees, for home country vacation or yearly leave.",
      "Drivers can apply for urgent leaves in case of emergency.",
      "Drivers can apply for sick leave if they are feeling unwell.",
      "Please select the day you want to take off.",
      "Request leave",
      "Your local leave is approved!",
      "Request a modification",
      "change dates",
      "You cannot book another local leave until you’ve used your last one.",
      "Request an annual leave",
      "Please choose start and end date of your leave",
      "Dates",
      "Select here start date",
      "Select here end date",
      "Your annual leave is pending approval",
      "Your leaves in a single place.",
      "Request an emergency leave",
      "Please choose start and end date of your leave",
      "Dates",
      "Please provide a reason for your leave",
      "Please provide a reason for your leave",
      "Leave reason",
      "Please upload the doctors medical certificate",
      "Request a sick leave",
      "Your sick leave is pending approval",
    ],
    id: 700,
    navigation: "hr",
    navigationText: "Leaves",
  },
  payslips: {
    payslips: "payslips",
    vectors: [
      "Payslips",
      "Payslip",
      "Please select a period of time",
      "Please select a month",
      "Earnings",
      "Basic",
      "Please select a period of time",
      "Driver Commissions",
      "CDM Tips",
      "CDM Tips",
      "Deductions",
      "Employee Advance Recovery",
      "Total earnings",
      "Total",
      "Total deductions",
      "Net Salary",
      "Download",
      "Payslips Download",
    ],
    id: 800,
    navigation: "hr",
    navigationText: "Payslips",
  },
  customerSatisfactionScreen: {
    customerSatisfactionScreen: "customerSatisfactionScreen",
    vectors: [
      "customer satisfaction",
      "all about customer satisfaction",
      "5 star",
      "4 star",
      "3 star",
      "2 star",
      "1 star",
      "driving skills",
      "knowledge of the route",
      "attitude and behaviour",
      "gromming and personal hygine",
      "communication skills",
      "car interior cleanliness",
      "car exterior cleanliness",
      "reviews",
      "customer satisfaction",
      "customer satisfaction",
      "customer satisfaction",
      "happy customer",
      "sad customer",
      "see what customer thinks about you",
      "other kips",
    ],
    id: 900,
    navigation: "customerSatisfactionScreen",
    navigationText: "Customer Satisfaction",
  },
  performanceScore: {
    performanceScore: "performanceScore",
    vectors: [
      "performance score",
      "commision",
      "pts",
      "your performance rating is based on your commision percentage",
      "the range comissions",
      "star comission raiting",
      "performance",
      "As a driver (User), I want understand how my  performance impact my score  (Action) so that I can improve them (Outcome)",
      "User should be able to access Performance score via the My Score card in My Score page",
      "The user should be able to see the value in stars",
      "He should be able to see the chart that explains the connection between stars and commission (and his position in it)",
      "There should be a section for help",
    ],
    id: 1000,
    navigation: "myScore",
    navigationText: "Performance Score",
  },
  vehicleAndPartnerHome: {
    vehicleAndPartnerHome: "vehicleAndPartnerHome",
    vectors: [
      "Vehicle and Partner",
      "Everything related to your vehicle and partner",
      "Your partner",
      "Your current vehicle",
      "Night shift",
      "Report vehicle status",
      "Change vehicle",
      "Change vehicle",
      "Change vehicle",
      "Get a permanent vehicle here",
      "Vehicle allocation",
      "Maintenance",
      "Vehicle maintenance",
      "Periodic, ondemand, history",
      "Take over",
      "Take",
      "Get a permanent vehicle here",
      "It looks like you dont have a permanent vehicle assigned, please search for one via Vehicle allocation",
      "Here youll be able to search for a permanent vehicle and/or partner.",
      "Your search preferences",
      "Available night shift",
      "Available day shift",
      "Send partnership request",
      "partnership",
      "search partner",
      "You sent a partnership request",
      "Your request should be answered in around 30 minutes.",
      "No answer from the partner. Your request has been escalated to Operations.Please wait.",
      "Manohar has accepted your partnership request!",
      "Please proceed with takeover",
      "Please go to the office, get the keys and locate the vehicle to start the inspection for takeover",
      "inspection",
      "Damage check",
      "Are there any damages?",
      "Vehicle maintenance",
      "Damage check",
      "sent you a partnership request.",
      "Rejection reasons",
      "Partner rejection",
      "Please specify the reason for the partner rejection",
      "Your rejection request is under review with Operations",
      "Operations assigned you a partner. ",
      "Vehicle rejected",
      "Car model",
      "Damages",
      "Take 4 pictures of your vehicle (all the 4 sides)",
      "Temporary vehicle allocation",
      "Here youll be able to search for a temporary vehicle for your shift",
      "Opportunities",
      "Update list",
      "Do you want to reserve this vehicle?",
      "Your temporary partner",
      "reserved",
      "is your  partner for the next shift",
      "Get in contact with him to define logistics",
      "Temporary",
      "time being",
      "Your temporary partner",
      "Your temporary vehicle",
      "Report vehicle status",
      "Maintenance",
      "Vehicle maintenance",
      "Breakdown",
      "You will not be charged for the current damages",
    ],
    id: 1100,
    navigation: "vehicleAndPartnerHome",
    navigationText: "Vehicle And Partner",
  },
  MyPartnerDetail: {
    MyPartnerDetail: "MyPartnerDetail",
    vectors: [
      "My Partner",
      "Everything related to your partner",
      "Partner shift",
      "Night shift",
      "Location",
      "Age group",
      "Nationality",
      "Mobile number",
      "Partner change",
      "Partner",
      "change",
      "Your temporary partner",
      "temporary",
      "partner",
    ],
    id: 1200,
    navigation: "vehicleAndPartnerHome",
    navigationText: "My Partner Detail.",
  },
  reportAccident: {
    profile: "reportAccident",
    vectors: [
      "Accident Management",
      "Is recovery required?",
      "Is recovery required?",
      "When did the accident occur?",
      "Accident Management",
      "Upload police paper (PDF only)",
      "Accident Management",
      "Whats the police report status?",
      "Select Report Status here",
      "Police Report Status",
      "Police report reference number",
      "Upload driving license (PDF only)",
      "Is the vehicle held by the police?",
      "Is the vehicle held by the police?",
      "Driving license",
      "Police report reference number",
      "Recovery required",
      "toe truck",
      "pickup",
      "pick up",
      "Police Report",
      "Police paper",
      "Police report reference number",
      "Vehicle held by police",
      "Police station details",
      "I am not injured",
      "Your accident has been reported",
      "reported accident",
      "accident",
      "reported",
      "help",
      "As a driver (User), I want to have a quick and accessible way to report accidents that occur during my shifts through the app (Action) so that I can be assured that the company is notified (Outcome)",
      "User should be able to access the Accident Management section from the main menu",
      "The user should be prompted first if the vehicle recovery is required or not",
      "The user should be prompted date and time of the accident",
      "The user should be asked police intervention details (if needed)",
      'The user should provide the police report status and police report pdf as mandatory except "waiting for police paper/approval" case',
      "The user should be able to add additional remarks",
      "A popup should reassure the user that the report has been sent",
      "As a driver (User), I want to have a quick and accessible way to report accidents that immobilise my vehicle (Action) so that I can be assured that the company is notified and that the tow truck comes for the rescue (Outcome)",
      "User should be able to access the Accident Management section from the main menu",
      "The user should be prompted first if the vehicle recovery is required or not",
      "The user should be able to provide its location, via GPS, searching the address or pin point on the map",
      "The user should be asked police intervention details (if needed)",
      'The user should provide the police report status and police report pdf as mandatory except "waiting for police paper/approval" case',
      "The user should be able to add additional remarks",
      "A popup should reassure the user that the report has been sent and that a tow truck is coming for the rescue",
    ],
    id: 1300,
    navigation: "reportAccident",
    navigationText: "Report Accident.",
  },
  profile: {
    profile: "profile",
    vectors: [
      "profile",
      "profile Photo",
      "profile",
      "edit Profile",
      "profile",
      "photo",
      "upload",
      "new photo",
      "upload photo",
      "name",
      "profile name",
      "display name",
      "my name",
      "meter id",
      "meter",
      "employee id",
      "id",
      "contact details",
      "contact",
      "email",
      "home",
    ],
    id: 1400,
    navigation: "profile",
    navigationText: "Profile.",
  },
  helpSupport: {
    helpSupport: "helpSupport",
    vectors: [
      "Help & Support",
      "Find out all the challenges and see the details.",
      "Most Common Topics",
      "Leaves",
      "Payslips",
      "My score",
      "Accident Management",
      "Do you need help?",
      "Solve all your problems here",
      "Need more help?",
      "Find out all the challenges and see the details.",
      "We help you with your personal data.",
      "My Profile",
      "We help you to solve your tickets.",
      "We explain how your score works and help you improve it!",
      "My Score",
      "My Finance",
      "We help you improve your performance.",
      "My Documents",
      "Request and download a copy.",
      "Request a leave or modify local leaves in case of urgency.",
      "Leaves",
      "Personal Help",
      "We will help you to know to act in these situations.",
      "We help you find an appointment for car maintenance.",
      "Do you have any question about your vehicle or partner? We help you to solve it.",
      "We help you to solve your Late Log in.",
    ],
    id: 1500,
    navigation: "helpSupport",
    navigationText: "Help Support.",
  },
  VideoListingScreen: {
    helpSupport: "VideoListingScreen",
    vectors: [
      "Training Hub",
      "Here you'll find all the available courses, online and in-person.",
      "Upcoming events",
      "Soft Skills Class",
      "Training room 3",
      "Driving Skills Class",
      "View All Training Events",
      "Trainings Videos",
      "View All Training Videos",
      "View All Training History",
      "Customer Service Excellence Course",
      "Route Training E Learning Video",
      "Route Training E Learning Video",
      "Take Assessment",
      "Provide Feedback",
      "Soft Skills Assessment",
      "Please complete your assessment",
      "New Training Video Upload",
      "General Skills Assessment has been assigned to you, please complete",
    ],
    id: 1600,
    navigation: "VideoListingScreen",
    navigationText: "Training and videos",
  },
  ticketCenter: {
    ticketCenter: "ticketCenter",
    vectors: [
      "Ticket Center",
      "All your pending and resolved tickets in a single place.",
      "Action needed",
      "Ticket",
      "P&C needs more information from you",
      "Pending",
      "Waiting for feedback",
      "Your issue has been resolved, please rate the service.",
      "Open new ticket",
      "Open",
      "new ticket",
      "ticket",
      "Open new",
      "Ticket created",
      "Reason",
      "Remarks",
      "Reply to P&C",
      "operator",
      "Cancel request",
      "from Ops",
      "History",
      "Enter additional information",
      "Wait for P&C to review your request",
      "Office visit not required",
      "Office visit",
      "not required",
      "Office visit required",
      "Attachments sent by P&C",
      "Waiting for feedback",
      "Pending",
      "Closed",
      "Closed tickets",
      "Ticket OTP",
      "Ticket OTP",
      "Office visit",
      "Are you sure you want to cancel?",
      "Open a new ticket",
      "Office visit required, P&C office.",
      "Office visit required, P&C office.",
      "Office visit required, P&C office.",
      "Select a time for your appointment",
      "Select a time for your appointment",
      "appointment",
      "your appointment",
      "Customer refund",
      "Your office visit has been booked.",
      "Remember to be on time and to show this OTP code once there",
      "I have a problem with the app",
      "Closing comments",
      "Attachments sent by P&C",
      "chat",
      "chat with",
      "How do you rate the process of handling your ticket?",
      "Send feedback",
      "How do you rate the process of handling your ticket?",
      "Thank you for your feedback!",
      "Closed tickets",
      "Download",
      "Download",
      "Give feedback",
      "Your “Careem issue” ticket has been closed. Please provide your feedback.",
      "Careem issue",
    ],
    id: 1600,
    navigation: "ticketCenter",
    navigationText: "Ticket Center",
  },
  profileDetail: {
    profileDetail: "profileDetail",
    vectors: [
      "makhani number",
      "want",
      "makhani",
      "address",
      "uae address",
      "phone number",
      "contact number",
      "personal details",
      "personal",
      "home",
      "home country",
      "country",
      "details",
      "country number",
      "emergancy number",
      "emergancy contact",
      "driver",
      "driver details",
      "RTA",
      "permit",
      "Nationality",
      "Dependents",
      "Education",
      "Date of birth",
      "Traffic file number",
      "License expiry date",
      "License issue date",
      "License number",
      "License number",
      "RTA permit expiry date",
      "RTA permit number",
      "Mobile number change",
      "Your email has been changed",
      "Makani number",
      "Please type your new Makani number",
      "Please provide your location",
      "Local UAE address",
      "Your location",
      "profile",
      "details",
      "edit profile",
      "edit profile home country",
    ],
    id: 105,
    navigation: "profile",
    navigationText: "Profile details.",
  },
  vehicleMaintenance: {
    profileDetail: "vehicleMaintenance",
    vectors: [
      "Maintenance",
      "All your cars services in a single place",
      "Upcoming appointments",
      "Periodic maintenance",
      "Ondemand maintenance",
      "Previous maintenance",
      "Maintenance",
      "Abnormal Sound",
      "A/C",
      "AC not working",
      "Abnormal Sound",
      "Additional Damages",
      "Air Leakage",
      "ALQ",
      "Axel",
      "Battery",
      "BodyShop",
      "Brakes",
      "Breakdown",
      "Cooling Sytem",
      "Electrical",
      "Engine",
      "Engine noise",
      "Engine oil change",
      "Full Service",
      "Gauges",
      "Gear oil change",
      "General",
      "Inspection",
      "Lighting",
      "Major Service",
      "Minor Service",
      "NEW",
      "Preventive",
      "Radiator",
      "RAS",
      "Steering",
      "Suspension Sytem",
      "Suspension System",
      "Tire",
      "Tire Change",
      "Tire change",
      "Transmission",
      "Wheel",
      "Periodic Maintenance",
      "What service you need?",
      "Major",
      "Minor",
      "Book appointment",
      "Great! Your periodic maintenance has been booked",
      "Did you have a breakdown?",
      "On Demand Maintenance",
      "What service you need?",
      "On Demand Maintenance",
      "Breakdown",
      "Could you provide your current location?",
      "stuck",
      "broke down",
      "Dont worry, a tow truck is coming to pick you up. ",
      "tow truck",
      "pick up",
      "pickup",
    ],
    id: 105,
    navigation: "vehicleMaintenance",
    navigationText: "Vehicle Maintenance",
  },
  myCollections: {
    myCollections: "myCollections",
    navigationText: "Your Collections",
    vectors: [
      "My Finances",
      "Finances",
      "Everything related to your collections, commissions and outstanding",
      "Select a date",
      "Days collections",
      "collections",
      "Commission",
      "Days worked",
      "Surcharges",
      "Shift collections details",
      "Day shift collections",
      "Night shift",
      "Day shift",
      "Days worked",
      "Collections forecast",
      "Based on you current collections and your commission percentage, your collection forecast is:",
      "Estimated value",
      "To achieve it, in the next days you will have to collect at least per day.",
      "Outstanding",
      "Total Outstanding",
      "Outstanding details",
      "Internal Fines",
      "RTA Fines",
      "Account Statement",
      "Please choose Start and End date to create your report.",
      "Dates",
      "Remaining outstanding",
      "Outstanding details",
      "QC Fine",
      "HALA PENALTY",
      "Deducted from Commission Journal",
      "Download",
      "Fine enquiry",
      "Your fines",
      "Fine enquiry",
      "Dispute fine",
      "CT",
      "Fine dispute",
      "Your collections are not yet available.",
      "Please do your first deposit to access this functionality",
      "business",
      "kamaya",
      "kamai",
      "kamaya",
      "kaam",
      "As a driver (User), I want to have in-depth insights about my collections (Action) so that I can understand my data better and reach my goals (Outcome)",
      "User should be able to access My Collections via My Finance page",
      "User will automatically see last day of cash deposit but he should be able to choose other dates",
      "He will see the Day’s Collections and the Daily avg",
      "He should see a graph that shows the selected date collections, his past collections of the month (2nd until the last cash deposit), and the fluctuations of his daily avg",
      "He should see his total collections of the month, commissions, surcharges and numbers of days worked",
      "He should see a partial view of the days he has worked in night or day shifts, together with all the partial collections and commissions",
      "He should see his collections forecast (expected collection at the end of the month) based on his current daily avg and expected commission",
      "He should be able to change his expected commission to see the changes in the estimated collections",
      "A message should provide him insight on how to reach the selected commission in the remaining days ",
    ],
    id: 100,
    navigation: "myCollections",
  },
  onDemandMaintanance: {
    onDemandMaintanance: "onDemandMaintanance",
    vectors: [
      "Maintenance",
      "Aapke gaadi ki sabhi services ek jagah par",
      "Aapki vartaman gaadi",
      "Aapka calendar",
      "Aane wale appointments",
      "Aapke paas koi booking nahi hai",
      "Maintenance",
      "Aavritik maintenance",
      "On-demand maintenance",
      "Pichla maintenance",
      "Pichla maintenance",
      "Aapki vartaman gaadi",
      "Asamanya Awaz",
      "Battery",
      "Cooling System",
      "Electrical",
      "Aavritik Maintenance",
      "Aapko kis prakar ki service chahiye?",
      "Mukhya",
      "Chhoti",
      "Aavritik Maintenance",
      "Aapko kis prakar ki service chahiye?",
      "Aapke liye sabse acchi date kya hai?",
      "Appointment book karein",
      "Shresth! Aapka aavritik maintenance book ho gaya hai",
      "Aapke gaadi ki sabhi services ek jagah par",
      "Kya aapka breakdown hua?",
      "Services List",
      "A/C",
      "Asamanya Awaz",
      "Atirikt Nuksan",
      "Axel",
      "Battery",
      "BodyShop",
      "Brakes",
      "Cooling System",
      "Electrical",
      "Engine",
      "Gauges",
      "Lighting",
      "Service prakar",
      "Maintenance prakar",
      "Workshop",
      "Shresth! Aapka on-demand maintenance book ho gaya hai",
      "Kya aap apna vartaman sthal bata sakte hain?",
      "Kya aapke paas koi atirikt tippaniyan hain?",
      "Chinta na karein, ek tow truck aapko uthane aa raha hai.",
      "Pickup",
      "Nirdharit maintenance",
      "Aapko saal bhar ki gaadi ki samiksha ke liye ek workshop mein appointment book karna hoga",
      "Al Quoz mein saal bhar ki gaadi ki samiksha",
      "Aane wale appointments",
      "Maintenance",
      "As a driver (User), I want to be able to easily book a on demand maintenance (Action) so that I can ensure my vehicle remains in optimal condition and that the booking fits in my personal schedule. (Outcome)",
      "User should be able to book a On Demand Maintenance from the Maintenance page",
      "He should be able to select multiple services, the workshop, the date and time of the appointment",
      "The calendar should provide available dates and time slots",
      "The user will need a confirmation that the booking has been confirmed",
      "As a driver (User), I want to be able to notify the workshop as soon as possible when my vehicle has a breakdown (Action) so that I can receive assistance promptly and minimise disruptions to my work.(Outcome)",
      "User should be easily access the Breakdown option from Accident management or Maintenance",
      "The user should be able to provide his current location, via GPS coordinates or to search for an address",
      "Once the request for a tow truck is sent, the user should be able to track the tow truck movement until his location",
    ],
    id: 100,
    navigationText: "Your Finance",
    navigation: "vehicleMaintenance",
  },
  previousMaintenance: {
    previousMaintenance: "previousMaintenance",
    vectors: [
      "Previous maintenance",
      "completed maintenance",
      "old Maintenance",
    ],
    id: 100,
    navigationText: "Maintenance",
    navigation: "vehicleMaintenance",
  },
  periodicMaintenance: {
    periodicMaintenance: "periodicMaintenance",
    vectors: [
      "Scheduled maintenance",
      "Annual review",
      "You need to book an appointment at a workshop for the Annual vehicle review",
      "Schedule appointment",
      "What date fit best for you?",
      "Available dates",
      "Not available",
      "At what time do you want to book it?",
      "Book appointment",
      "Great! Your scheduled maintenance has been booked",
      "Periodic maintenance",
      "As a driver (User), I want to be able to easily book a periodic maintenance (Action) so that I can ensure my vehicle remains in optimal condition and that the booking fits in my personal schedule. (Outcome)",
      "User should be able to book a Periodic Maintenance from the Maintenance page",
      "He should be able to select the kind of maintenance, the workshop, the date and time of the appointment",
      "The calendar should provide available dates and time slots",
      "The user will need a confirmation that the booking has been confirmed",
    ],
    id: 100,
    navigationText: "Maintenance",
    navigation: "vehicleMaintenance",
  },
  needMoreHelp: {
    needMoreHelp: "needMoreHelp",
    vectors: [
      "Help and support",
      "Frequently Asked question",
      "Most Common Topics",
      "Find out all the challenges and see the details.",
      "My Documents help",
    ],
  },
  vehicleTakeOverStep1: {
    vehicleTakeOverStep1: "vehicleTakeOverStep1",
    vectors: [
      "Vehicle take-over",
      "Here you can take-over a vehicle from the office or from other drivers.",
      "Your vehicle",
      "Toyota Prius",
      "Nightshift",
      "Take 4 pictures of your vehicle (all the 4 sides)",
      "Additional comments",
      "You will not be charged for the current damages",
      "Damage check",
      "Are there any damages?",
      "Awesome! You can now start your shift",
      "Takeover vehicle",
      "Reject vehicle",
    ],
    id: 1500,
    navigationText: "Vehicle TakeOver",
    navigation: "vehicleTakeOverStep1",
  },
  moreTripsScreen: {
    moreTripsScreen: "moreTripsScreen",
    vectors: ["do more trips", "Find where we can do more trips"],
    id: 1500,
    navigationText: "",
    navigation: "moreTripsScreen",
  },
  createTicket: {
    createTicket: "createTicket",
    vectors: [
      "Ticket Center",
      "All your pending and resolved tickets in a single place.",
      "Action needed",
      "Ticket",
      "P&C needs more information from you",
      "Pending",
      "Waiting for feedback",
      "Your issue has been resolved, please rate the service.",
      "Open new ticket",
      "Open",
      "new ticket",
      "ticket",
      "Open new",
      "Ticket created",
      "Reason",
      "Remarks",
      "Reply to P&C",
      "operator",
      "Cancel request",
      "from Ops",
      "History",
      "Enter additional information",
      "Wait for P&C to review your request",
      "Office visit not required",
      "Office visit",
      "not required",
      "Office visit required",
      "Attachments sent by P&C",
      "Waiting for feedback",
      "Pending",
      "Closed",
      "Closed tickets",
      "Ticket OTP",
      "Ticket OTP",
      "Office visit",
      "Are you sure you want to cancel?",
      "Open a new ticket",
      "Office visit required, P&C office.",
      "Office visit required, P&C office.",
      "Office visit required, P&C office.",
      "Select a time for your appointment",
      "Select a time for your appointment",
      "appointment",
      "your appointment",
      "Customer refund",
      "Your office visit has been booked.",
      "Remember to be on time and to show this OTP code once there",
      "I have a problem with the app",
      "Closing comments",
      "Attachments sent by P&C",
      "chat",
      "chat with",
      "How do you rate the process of handling your ticket?",
      "Send feedback",
      "How do you rate the process of handling your ticket?",
      "Thank you for your feedback!",
      "Closed tickets",
      "Download",
      "Download",
      "Give feedback",
      "Your “Careem issue” ticket has been closed. Please provide your feedback.",
      "Careem issue",
    ],
    id: 1500,
    navigationText: "Create Ticket",
    navigation: "createTicket",
  },
  VehiclePartnerSearchList: {
    VehiclePartnerSearchList: "VehiclePartnerSearchList",
    vectors: [
      "search",
      "partner",
      "find partner",
      "has accepted your partnership request!",
      "Your partner",
      "find Your partner",
      "Contact partner",
      "You sent a partnership request",
      "Your request should be answered in around 30 minutes.",
      "They should reply in less then 30 minutes.",
      "Here you’ll be able to search for a permanent vehicle and/or partner.",
    ],
    id: 1500,
    navigationText: "Vehicle Partner Search",
    navigation: "VehiclePartnerSearchList",
  },
  breakDownScreen: {
    breakDownScreen: "breakDownScreen",
    vectors: [
      "Could you provide your current location?",
      "Breakdown",
      "On Demand Maintenance",
      "Did you have a breakdown?",
      "A/C",
      "Abnormal Sound",
      "Additional Damages",
      "Axel",
      "Battery",
      "BodyShop",
      "Brakes",
      "Cooling System",
      "Electrical",
      "Engine",
      "Gauges",
      "Lighting",
      "Send my current location",
      "Send my current location",
      "Maintenance type breakdown",
      "Don’t worry, a tow truck is coming to pick you up. ",
    ],
    id: 1500,
    navigationText: "Break Down Screen",
    navigation: "breakDownScreen",
  },
  behaviourBonus: {
    behaviourBonus: "behaviourBonus",
    vectors: [
      "Do you want to win400?",
      "Reach 4.3 in your behaviour score to get the bonus!",
      "As a driver (User), I want to access the Behaviour bonus (Action) so that I can see the requirements and my current status (Outcome)",
      "User should be able to access Behaviour bonus via a card in My Score page",
      "The page should provide the user all the information needed to get the bonus",
      "The user should understand if he’s eligible or not for it",
    ],
    id: 1500,
    navigationText: "Behaviour Bonus",
    navigation: "behaviourBonus",
  },
  challengesList: {
    challengesList: "challengesList",
    vectors: [
      "Challenges",
      "Find out all the challenges and see the details.",
      "CT Champions",
      "2 weeks left for this challenge",
      "Fly for free",
      "2 weeks left for this challenge",
      "Drive a Taxi & Win a Taxi",
      "2 weeks left for this challenge",
      "CT Champions",
      "Drive a taxi & win a taxi",
    ],
    id: 1500,
    navigationText: "Challenges List",
    navigation: "challengesList",
  },
  challengeDetails: {
    challengeDetails: "challengeDetails",
    vectors: [
      "Drive a Taxi & Win a Taxi",
      "For best behaviours",
      "Reward:",
      "De‐fleeted Taxi",
      "Process:",
      "Yearly",
      "Drive a taxi & win a taxi",
      "Min 3 years Tenure",
      "No Traffic fines",
      "No Quality violations",
      "No Customer complains",
      "Fly for free",
      "For top generators",
      "Plane ticket to your home coutry",
      "Process:",
      "Requirements",
      "Income 37.5% & 40%",
      "No Traffic fines",
      "No Quality violations",
      "No Customer complains",
      "CT Champions",
      "For best behaviours",
      "Quarterly",
      "CT Champions",
      "For new drivers",
      "No Accidents",
      "For existing drivers",
      "No Traffic fines",
      "No Customer complains",
      "No Quality violations",
    ],
    id: 1500,
    navigationText: "challengeDetails",
    navigation: "challengeDetails",
  },
  behaviourScore: {
    behaviourScore: "behaviourScore",
    vectors: [
      "Behaviour score",
      "pts",
      "Your behaviour rating is based on all of the following parameters and directly affects your commission percentage.",
      "Hala Online Rate",
      "Outstanding",
      "Unauthorized leave",
      "RTA Quality",
      "RTA Complaints",
      "Hala Acceptance",
      "Logged off KM%",
      "Traffic Fines",
      "Revenue KM%",
      "Behaviour",
      "Attitude and Behaviour",
      "As a driver (User), I want understand how my behaviour score is calculated (Action) so that I can learn how to do better (Outcome)",
      "User should be able to access Behaviour score via the My Score card in My Score page",
      "The user should be able to see the value in stars",
      "He should be able to see all the different parameters that generate the score",
      "The Customer Satisfaction score should be highlighted and clickable from the user",
      "In the Customer Satisfaction page, the user should be able to view in details all the ratings that customers provided in all the different categories and their comments.",
    ],
    id: 1500,
    navigationText: "Behaviour Score",
    navigation: "behaviourScore",
  },
  scoreHistory: {
    scoreHistory: "scoreHistory",
    vectors: [
      "Score history",
      "Go through months of your score",
      "pts",
      "July’s score",
      "Performance",
      "Behaviour",
      "Customer satisfaction",
      "See what your customers think about you. ",
      "reviews",
      "Success Trends",
      "Improvement trends",
      "+1.3 points compared to last month",
      "RTA Quality",
      "+0.8 points compared to last month",
      "Outstanding",
      "RTA Complaints",
      "As a driver (User), I want to check the history of my score (Action) so I can understand it and improve  (Outcome)",
      "User should be able to access Score history via the My Score card in My Score page",
      "The user should be able to change the year",
      "The user should be able to scroll through the graph to select a different month",
      "He should see his overall score + Partial and Behaviour",
      "At the bottom, he should see his Success trends and improvement trends",
    ],
    id: 1500,
    navigationText: "Score History",
    navigation: "scoreHistory",
  },
  driverComparisionScreen: {
    driverComparisionScreen: "driverComparisionScreen",
    vectors: [
      "Driver Comparison",
      "You",
      "Top Driver",
      "Performance",
      "Behaviour",
      "Need to focus on",
      "Fines",
      "Complaints",
      "As a driver (User), I want to learn form other driver (Action) so that I can be better an improve (Outcome)",
      "User should be able to access Driver comparison via a card in My Score page",
      "The page should provide a comprehensible chart between driver’s KPIs and the ones of the top driver of the month",
      "The tiles in the graph should focus only on the improvement areas, giving the drivers suggestions",
    ],
    id: 1500,
    navigationText: "Driver Comparision Screen",
    navigation: "driverComparisionScreen",
  },
  outStanding: {
    outStanding: "outStanding",
    vectors: [
      "Outstanding",
      "Outstanding amount",
      "Updated: Friday, January 13, 2024",
      "Total Outstanding",
      "Internal Fines",
      "RTA Fines",
      "Remaining Outstanding",
      "As a driver (User), I want to see how much my outstanding are (Action) so that I can plan better my financial life (Outcome)",
    ],
    id: 1500,
    navigationText: "Out Standing",
    navigation: "outStanding",
  },
  accountStatement: {
    accountStatement: "accountStatement",
    vectors: [
      "Account Statement",
      "Please choose Start and End date to create your report.",
      "Dates",
      "Download Account Statement",
      "Remaining outstanding",
      "Outstanding details",
      "Download",
      "As a driver (User), I want to see and download all my transactions within a specified period (Action) so that I have a better understanding and overall view of my financial situation (Outcome)",
    ],
    id: 1500,
    navigationText: "Account Statement",
    navigation: "accountStatement",
  },
  fines: {
    fines: "fines",
    vectors: [
      "Fine enquiry",
      "Dispute fine",
      "how much fine i have?",
      "Your fines",
      "Fine enquiry",
      "Dispute fine",
      "RTA fine",
      "Fine dispute",
      "As a driver (User), I want to see all my fines within a specified period (Action) so that I can dispute them and have a better understanding of my financial situation (Outcome)",
    ],
    id: 1500,
    navigationText: "Fines",
    navigation: "fines",
  },
};
